### ISSUE TITLE
2. farben

### ISSUE THREAD

**Issue by JacobLoe** [JacobLoe/dominant_color_in_video#2]
- die liste der farben einem farbraum zuordnen (hsv, rgb ...)

**Comment by JacobLoe** [comment]
https://www.rapidtables.com/web/color/RGB_Color.html

**Comment by chrstn-hntschl** [comment]
nach Aussage des Projektpartners sind das einfach die HTML/CSS Farben - damit müsstest Du fündig werden

**Comment by JacobLoe** [comment]
hab die schon gefunden, bis auf purple4 und skin, die hab ich jetzt erstmal
selber auf etwas festgelegt

Jacob Löbkens

Behlertstraße 37
14467 Potsdam
Tel.: +49171 9823505
E-Mail: jcbl423@gmail.com

**Comment by chrstn-hntschl** [comment]
RGB values for 'purple4' 'skin' - nichts offizielles?
