### ISSUE TITLE
5. farb akzente im video

### ISSUE THREAD

**Issue by JacobLoe** [JacobLoe/dominant_color_in_video#5]
- highlight farben die oft im histogram vorkommen im vergleich zu den dominanten farben

**Comment by chrstn-hntschl** [comment]
das würde ich gerne etwas zurückstellen - nach Aussage des Projektpartners werden diese Akzente sehr selten annotiert, sodass das auch manuell erfolgen kann.

**Comment by JacobLoe** [comment]
dann mach ich den hier erstmal zu
